# Generated by Django 4.2.7 on 2023-11-21 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted', models.BooleanField(default=False, editable=False, verbose_name='Borrado')),
                ('_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('path', models.CharField(editable=False, max_length=255, verbose_name='Path')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted', models.BooleanField(default=False, editable=False, verbose_name='Borrado')),
                ('_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('other_attributes', models.JSONField(blank=True, null=True, verbose_name='Otros atributos')),
                ('stock', models.SmallIntegerField(default=0, editable=False, verbose_name='Cantidad disponible')),
                ('price_fake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('price_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['product', 'size', 'color', '-price_real'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted', models.BooleanField(default=False, editable=False, verbose_name='Borrado')),
                ('_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('purchase_urls', models.JSONField(blank=True, null=True, verbose_name='Links de compra')),
                ('stock', models.SmallIntegerField(default=0, editable=False, verbose_name='Cantidad disponible')),
                ('price_fake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('price_real', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category', 'name', '-price_real'],
            },
        ),
    ]
