# Generated by Django 4.2.7 on 2023-11-18 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
